language: generic 

sudo: required
services:
  - docker

before_install:
  - docker build -t antonio28120/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true antonio28120/docker-react npm run test -- --coverage